### ISSUE TITLE
Caffe error

### ISSUE THREAD

**Issue by mh-ih** [tringwald/UAV-Net#1]
Hello and thanks for sharing your work.
How can I fix the following error raised by running "draw_detections.py"?
Is it depend on caffe installation or version?

> [libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 301:14: Message type "caffe.LayerParameter" has no field named "norm_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0601 17:34:43.921265 24085 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: models/UAVDT/UAVNet_100_5x5_5boxes/deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by tringwald** [comment]
Thank you for your interest in my work. The error sounds like you have installed the wrong Caffe version. Please make sure you actually use the [repository](https://github.com/weiliu89/caffe/tree/ssd) mentioned in the README and also make sure that you have checked out the "ssd" branch of that repository.

**Comment by mh-ih** [comment]
Thank you so much.
Is it possible to train the network on a new dataset from scratch?

**Comment by tringwald** [comment]
It should definitely be possible, please refer to the SSD repository for that. However, note that re-training the pruned network and pruning a re-trained network will yield different results.

**Comment by mh-ih** [comment]
Thanks for the quick reply

**Comment by mh-ih** [comment]
Which method is better?
Train the SSD source code on new data, finally use "auto_prune.py". Or first use "auto_prune.py" on a SSD pretrained model, then train it?
Have I figured it out correctly?
